package com.pr.se.cash_manager;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class ExpenseTest {
    private Expense expense;
    private static final double DELTA = 1e-15;

    @Before
    public void setUp() throws Exception {
        expense = new Expense(234.1, "23.05.2006", "Restaurant", "mums birthday");
    }
    @Test
    public void getRecurring_id() throws Exception {
        String expected = expense.getRecurring_id();
        String actual = null;
        assertEquals("Fields didn't match", expected, actual);
    }

    @Test
    public void setRecurring_id() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getCategory() throws Exception {
        String expected = expense.getCategory();
        String actual = "Restaurant";
        assertEquals("Fields didn't match", expected, actual);
    }

    @Test
    public void setCategory() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getDescription() throws Exception {
        String expected = expense.getDescription();
        String actual = "mums birthday";
        assertEquals("Fields didn't match", expected, actual);
    }

    @Test
    public void setDescription() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getDate() throws Exception {
        String expected = expense.getDate();
        String actual = "23.05.2006";
        assertEquals("Fields didn't match", expected, actual);
    }

    @Test
    public void setDate() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getSum() throws Exception {
        double expected = expense.getSum();
        double actual = 234.1;
        assertEquals(expected, actual, DELTA);
    }

    @Test
    public void setSum() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void addImage() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void deleteImage() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getImages() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getId() throws Exception {
        String actual = expense.getId();
        assertTrue(actual != null && !actual.equals(""));
    }

    @Test
    public void hashCodeTest() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void equalsTest() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

}