package com.pr.se.cash_manager;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Created by theresaprinz on 03.07.17.
 */
public class FilterTest {
    @Test
    public void getFilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setFilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void isCheck() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setCheck() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getSubfilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setSubfilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

}