package com.pr.se.cash_manager;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Created by theresaprinz on 03.07.17.
 */
public class RecurringExpenseTest {
    @Test
    public void getDate_to() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setDate_to() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getIntervall() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setIntervall() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void getDate_next() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void setDate_next() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

}