package com.pr.se.cash_manager;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Created by theresaprinz on 03.07.17.
 */
public class RWTest {
    @Test
    public void readExpenses() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void writeExpenses() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void readCategories() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void writeCategories() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void readFilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

    @Test
    public void writeFilter() throws Exception {
        //TODO autogenerated Test
        assertTrue(false);
    }

}